import "@/styles/global.scss";
import Header from "@/components/layout.js/Header";
import Footer from "@/components/layout.js/Footer";

export const metadata = {
  title: "PT Bumi Asri Pratama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
